export enum ActionTypes {
  FETCH_SEARCH_RESULT_REQUEST = 'SEARCH/FETCH_SEARCH_RESULT_REQUEST',
  FETCH_SEARCH_RESULT_FAILURE = 'SEARCH/FETCH_SEARCH_RESULT_FAILURE',
  FETCH_SEARCH_RESULT_SUCCESS = 'SEARCH/FETCH_SEARCH_RESULT_SUCCESS',
  FETCH_MORE_SEARCH_RESULT_REQUEST = 'SEARCH/FETCH_MORE_SEARCH_RESULT_REQUEST',
  FETCH_MORE_SEARCH_RESULT_FAILURE = 'SEARCH/FETCH_MORE_SEARCH_RESULT_FAILURE',
  FETCH_MORE_SEARCH_RESULT_SUCCESS = 'SEARCH/FETCH_MORE_SEARCH_RESULT_SUCCESS',
  CLEAR_ERROR = 'SEARCH/CLEAR_ERROR',
}
